### ISSUE TITLE
'End Conversation' Box Missing - Instructions not available even though it says it is

### ISSUE THREAD

**Issue by kurokittyzilla** [greenido/animal-joker#3]
Hello 

Explanation on how to add the 'End Conversation' box is missing even though it says it is available on the following step 4) Test your action. 
I am also missing the Actions on Google integration on the integration page.
Please see screenshots for reference. 

Looking for anyone who has had this problem and was able to solve it. 

Thanks!
 
<img width="737" alt="2018-01-18 18 32 50" src="https://user-images.githubusercontent.com/35522072/35090849-4e942ac0-fc7e-11e7-98ab-3be0a86c2dff.png">
<img width="867" alt="2018-01-18 18 32 43" src="https://user-images.githubusercontent.com/35522072/35090851-4edf8312-fc7e-11e7-955d-f1b5668c190f.png">

**Comment by greenido** [comment]
Thank you. I'm closing this one as I'm no longer with Google.
